### ISSUE TITLE
cannot make mlpolyr

### ISSUE THREAD

**Issue by MarisaKirisame** [nojb/mlpolyr#1]
make[1]: Entering directory '/home/marisa/Source/mlpolyr/rt'
cc -arch ppc -c -O2 mlpr-rt.c
cc: error: ppc: No such file or directory
cc: error: unrecognized command line option ‘-arch’; did you mean ‘-march=’?

is the script too old and need updating? I really want to try out mlpolyr but find the lack of docs frusturating.

**Comment by nojb** [comment]
This repository contains the original codebase. I haven't looked into it myself, but I imagine it will need a bit of tweaking to bring it up to date so that it can be compiled.

**Comment by ice1000** [comment]
> This repository contains the original codebase.

So there's an "original codebase"? Could you please give us some information about that? Like, a link containing the "original codebase", or someone we can contact for?

**Comment by nojb** [comment]
> > This repository contains the original codebase.
> 
> So there's an "original codebase"? Could you please give us some information about that? Like, a link containing the "original codebase", or someone we can contact for?

http://people.cs.uchicago.edu/~blume/mlpolyr/

**Comment by ice1000** [comment]
> > > This repository contains the original codebase.
> > 
> > 
> > So there's an "original codebase"? Could you please give us some information about that? Like, a link containing the "original codebase", or someone we can contact for?
> 
> http://people.cs.uchicago.edu/~blume/mlpolyr/

Thanks!
